[package]
name = "ebpf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ebpf_probe"
path = "src/main.rs"
test = false

[dependencies]
aya-ebpf = "0.1.1"
common = { path = "../common" }

[profile.dev]
panic = "abort"
debug = true

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1
panic = "abort"