[package]
name = "ebpf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ebpf-probe"
path = "src/main.rs"
test = false

[dependencies]
aya-ebpf = "0.1.1"
common = { path = "../common", default-features = false }

[unstable]
build-std = ["core", "alloc"]

[build]
target = "bpfel-unknown-none"


[profile.dev]
opt-level = 3
panic = "abort"

[profile.release]
opt-level = 3
panic = "abort"